package com.turnus.rota.engine

import java.util.Base64

/**
 * Encodes a [Pattern] compactly enough to travel in a URL fragment.
 *
 * The fragment matters: everything after `#` is never sent to the server in an
 * HTTP request, so a shared rota physically cannot reach the host — not even in
 * its access logs. Sharing therefore needs no backend and leaks nothing, which
 * is why this is a link rather than an account.
 *
 * The token is versioned because old installs will receive links generated by
 * newer ones. An unrecognised version must produce a clear "update the app"
 * message rather than a corrupted calendar, so [decode] reports it distinctly
 * from a link that is simply broken.
 *
 * ### Wire format, v1
 *
 * ```
 * v1.<base64url of>  anchorDay ";" codes ";" slots ";" name
 * ```
 *
 * - `codes` — comma-separated distinct shift ids, in first-seen order
 * - `slots` — one character per cycle day: `-` for off, else a base-36 index
 *   into `codes`
 * - `name` — last, and split with a limit, so it may contain `;` freely
 */
object ShareLink {

    const val VERSION: String = "v1"

    private const val OFF = '-'
    private const val FIELD = ';'
    private const val CODE_SEPARATOR = ','
    private const val RADIX = 36

    /**
     * @throws IllegalArgumentException if the pattern uses more than 36 distinct
     *   shift types, or a shift id containing the separator characters. Both are
     *   caller errors — ids are generated, not typed.
     */
    fun encode(pattern: Pattern): String {
        val codes = pattern.slots.filterNotNull().distinct()
        require(codes.size <= RADIX) {
            "share links support at most $RADIX distinct shift types, got ${codes.size}"
        }
        require(codes.none { it.contains(CODE_SEPARATOR) || it.contains(FIELD) }) {
            "shift ids must not contain '$CODE_SEPARATOR' or '$FIELD'"
        }

        val slots = buildString {
            pattern.slots.forEach { slot ->
                append(if (slot == null) OFF else Character.forDigit(codes.indexOf(slot), RADIX))
            }
        }

        val payload = listOf(
            pattern.anchor.value.toString(),
            codes.joinToString(CODE_SEPARATOR.toString()),
            slots,
            pattern.name,
        ).joinToString(FIELD.toString())

        val body = Base64.getUrlEncoder().withoutPadding()
            .encodeToString(payload.toByteArray(Charsets.UTF_8))

        return "$VERSION.$body"
    }

    /** Never throws. Every malformed input is a result, because the input is a stranger's URL. */
    fun decode(token: String): ShareLinkResult {
        val trimmed = token.trim().removePrefix("#")
        val dot = trimmed.indexOf('.')
        if (dot <= 0 || dot == trimmed.lastIndex) return ShareLinkResult.Malformed

        val version = trimmed.substring(0, dot)
        if (version != VERSION) return ShareLinkResult.UnsupportedVersion(version)

        val payload = try {
            String(Base64.getUrlDecoder().decode(trimmed.substring(dot + 1)), Charsets.UTF_8)
        } catch (_: IllegalArgumentException) {
            return ShareLinkResult.Malformed
        }

        val parts = payload.split(FIELD, limit = 4)
        if (parts.size != 4) return ShareLinkResult.Malformed

        val anchor = parts[0].toLongOrNull() ?: return ShareLinkResult.Malformed
        val codes = if (parts[1].isEmpty()) emptyList() else parts[1].split(CODE_SEPARATOR)
        val encodedSlots = parts[2]
        if (encodedSlots.isEmpty()) return ShareLinkResult.Malformed

        val slots = encodedSlots.map { ch ->
            if (ch == OFF) {
                null
            } else {
                val index = Character.digit(ch, RADIX)
                if (index < 0 || index >= codes.size) return ShareLinkResult.Malformed
                codes[index]
            }
        }

        return ShareLinkResult.Success(
            anchor = DayNumber(anchor),
            name = parts[3],
            slots = slots,
        )
    }

    /** The full shareable URL. The token goes after `#` — see the class note. */
    fun url(pattern: Pattern, base: String = "https://turnus.app/r/"): String =
        base + "#" + encode(pattern)

    /** Pulls the token out of an incoming URL, or null if there is no fragment. */
    fun tokenFrom(url: String): String? =
        url.substringAfter('#', "").ifEmpty { null }
}

sealed interface ShareLinkResult {

    /**
     * The pattern travelled intact. No id is invented here — ids are local to an
     * install, so the caller assigns one via [toPattern].
     */
    data class Success(
        val anchor: DayNumber,
        val name: String,
        val slots: List<String?>,
    ) : ShareLinkResult {
        fun toPattern(id: String): Pattern =
            Pattern(id = id, name = name, anchor = anchor, slots = slots)
    }

    /** Not a Turnus link, or damaged in transit. Offer nothing; say it plainly. */
    data object Malformed : ShareLinkResult

    /** A valid link from a newer app. Prompt to update rather than guessing. */
    data class UnsupportedVersion(val version: String) : ShareLinkResult
}
