package com.turnus.rota.engine

import java.util.Base64

/**
 * Encodes a [Pattern] compactly enough to be pasted into a message.
 *
 * ### Why letters, not ids
 *
 * A cycle is shared as the *letters* on the calendar — D, N, E, L — and never
 * as shift-type ids. Ids are generated per install: a rota shared by id would
 * name four shifts that exist on the sender's phone and on no other, and the
 * receiver would import a calendar of blanks. Letters are the thing both people
 * can see, and they are what the two of them already say to each other.
 *
 * It follows that the receiver's own shifts win. If their N starts at 18:00 and
 * the sender's starts at 19:00, the imported rota uses 18:00 — which is right,
 * because those are the hours the receiver actually works. What is being shared
 * is the shape of the rotation and where it falls, not somebody else's clock.
 *
 * ### Why a code and not a link
 *
 * A link needs a domain, a domain needs an owner, and a rota planner should not
 * need a server to let two people on the same shift compare rotas. [url] exists
 * for the day there is a domain, and takes its base as an argument so that no
 * caller can accidentally produce a link to a host nobody runs. Until then the
 * token travels on its own, in any messaging app, and is pasted back in.
 *
 * When it does travel as a URL the token goes in the fragment: everything after
 * `#` is never sent in an HTTP request, so a shared rota cannot reach the host —
 * not even its access logs.
 *
 * ### Wire format, v1
 *
 * ```
 * v1.<base64url of>  anchorDay ";" codes ";" slots ";" name
 * ```
 *
 * - `codes` — comma-separated distinct shift letters, in first-seen order
 * - `slots` — one character per cycle day: `-` for off, else a base-36 index
 *   into `codes`
 * - `name` — last, and split with a limit, so it may contain `;` freely
 *
 * The token is versioned because old installs will receive tokens generated by
 * newer ones. An unrecognised version must produce a clear "update the app"
 * message rather than a corrupted calendar, so [decode] reports it distinctly
 * from a token that is simply broken.
 */
object ShareLink {

    const val VERSION: String = "v1"

    private const val OFF = '-'
    private const val FIELD = ';'
    private const val CODE_SEPARATOR = ','
    private const val RADIX = 36

    /** `v` and digits, nothing else — see the version check in [decode]. */
    private val VERSION_SHAPE = Regex("v[0-9]+")

    /**
     * @param definitions every shift type the pattern's slots can name, keyed by
     *   id. The letters come from here.
     * @throws IllegalArgumentException if a slot names a shift that is not in
     *   [definitions], if the cycle uses more than 36 distinct letters, or if a
     *   letter contains a separator character. The first is a caller error; the
     *   last is reachable from the shift editor, where the letter is typed.
     */
    fun encode(pattern: Pattern, definitions: Map<String, ShiftDefinition>): String {
        val slotCodes = pattern.slots.map { slot ->
            slot?.let {
                definitions[it]?.code
                    ?: throw IllegalArgumentException("no shift type for id '$it'")
            }
        }

        val codes = slotCodes.filterNotNull().distinct()
        require(codes.size <= RADIX) {
            "share codes support at most $RADIX distinct shifts, got ${codes.size}"
        }
        require(codes.none { it.contains(CODE_SEPARATOR) || it.contains(FIELD) }) {
            "a shift letter must not contain '$CODE_SEPARATOR' or '$FIELD'"
        }

        val slots = buildString {
            slotCodes.forEach { code ->
                append(if (code == null) OFF else Character.forDigit(codes.indexOf(code), RADIX))
            }
        }

        val payload = listOf(
            pattern.anchor.value.toString(),
            codes.joinToString(CODE_SEPARATOR.toString()),
            slots,
            pattern.name,
        ).joinToString(FIELD.toString())

        val body = Base64.getUrlEncoder().withoutPadding()
            .encodeToString(payload.toByteArray(Charsets.UTF_8))

        return "$VERSION.$body"
    }

    /** Never throws. Every malformed input is a result, because the input is something a stranger typed. */
    fun decode(token: String): ShareLinkResult {
        val trimmed = token.withoutInvisibles().removePrefix("#")
        val dot = trimmed.indexOf('.')
        if (dot <= 0 || dot == trimmed.lastIndex) return ShareLinkResult.Malformed

        val version = trimmed.substring(0, dot)
        if (version != VERSION) {
            // "A newer version" only if it actually looks like one. Without
            // this, any sentence containing a full stop is reported as a code
            // from the future — and since whitespace is now stripped before
            // this point, a pasted message that merely *mentions* the app would
            // qualify. Prose is a malformed code, not a version problem.
            return if (VERSION_SHAPE.matches(version)) {
                ShareLinkResult.UnsupportedVersion(version)
            } else {
                ShareLinkResult.Malformed
            }
        }

        val payload = try {
            String(Base64.getUrlDecoder().decode(trimmed.substring(dot + 1)), Charsets.UTF_8)
        } catch (_: IllegalArgumentException) {
            return ShareLinkResult.Malformed
        }

        val parts = payload.split(FIELD, limit = 4)
        if (parts.size != 4) return ShareLinkResult.Malformed

        val anchor = parts[0].toLongOrNull() ?: return ShareLinkResult.Malformed
        val codes = if (parts[1].isEmpty()) emptyList() else parts[1].split(CODE_SEPARATOR)
        val encodedSlots = parts[2]
        if (encodedSlots.isEmpty()) return ShareLinkResult.Malformed

        val slots = encodedSlots.map { ch ->
            if (ch == OFF) {
                null
            } else {
                val index = Character.digit(ch, RADIX)
                if (index < 0 || index >= codes.size) return ShareLinkResult.Malformed
                codes[index]
            }
        }

        return ShareLinkResult.Success(
            anchor = DayNumber(anchor),
            name = parts[3],
            codes = slots,
        )
    }

    /**
     * Removes every character that carries no meaning but survives a paste.
     *
     * A code travels through a messaging app, an email client and a clipboard
     * before it gets here, and each of them is entitled to break a long
     * unbroken string across lines. What arrives is the same token with a
     * newline in the middle of it, and Base64 has no opinion about whitespace
     * other than to reject it — so the user is told their workmate's rota is
     * not a rota, in the one flow that gets this app its next user for free.
     *
     * Three families go, not one:
     *
     * - whitespace, including the Unicode space separators, for hard wrapping;
     * - non-breaking space, which `Char.isWhitespace` deliberately excludes and
     *   which is what several clients insert when they wrap;
     * - the format category `Cf` — zero-width space and joiners, the
     *   bidirectional marks, the byte-order mark, and the soft hyphen that
     *   text renderers leave behind at a wrap point.
     *
     * Stripping these cannot turn one valid token into a different valid one,
     * because none of them are in the token's alphabet. It can only rejoin a
     * token that was whole when it was sent.
     */
    private fun String.withoutInvisibles(): String = buildString(length) {
        this@withoutInvisibles.forEach { ch ->
            val invisible = ch.isWhitespace() ||
                Character.isSpaceChar(ch) ||
                Character.getType(ch) == Character.FORMAT.toInt()
            if (!invisible) append(ch)
        }
    }

    /**
     * The full shareable URL, for whenever there is a domain to put it on.
     *
     * [base] has no default on purpose: a default would be a link to a host
     * nobody owns, and the person it was sent to would get a 404 rather than a
     * rota. The token goes after `#` — see the class note.
     */
    fun url(pattern: Pattern, definitions: Map<String, ShiftDefinition>, base: String): String =
        base + "#" + encode(pattern, definitions)

    /** Pulls the token out of an incoming URL, or null if there is no fragment. */
    fun tokenFrom(url: String): String? =
        url.substringAfter('#', "").ifEmpty { null }
}

sealed interface ShareLinkResult {

    /**
     * The cycle travelled intact, as letters.
     *
     * No id is invented here. Ids are local to an install and the letters have
     * to be matched against the receiver's own shift types — which is a
     * decision about their data, not an encoding detail, so [toPattern] takes
     * the mapping rather than guessing at one.
     */
    data class Success(
        val anchor: DayNumber,
        val name: String,
        /** One entry per cycle day: a shift letter, or null for a day off. */
        val codes: List<String?>,
    ) : ShareLinkResult {

        /** The distinct letters used, in the order they first appear in the cycle. */
        val shiftCodes: List<String> get() = codes.filterNotNull().distinct()

        fun toPattern(id: String, name: String = this.name, idForCode: (String) -> String): Pattern =
            Pattern(
                id = id,
                name = name,
                anchor = anchor,
                slots = codes.map { code -> code?.let(idForCode) },
            )
    }

    /** Not a Turnus code, or damaged in transit. Offer nothing; say it plainly. */
    data object Malformed : ShareLinkResult

    /** A valid code from a newer app. Prompt to update rather than guessing. */
    data class UnsupportedVersion(val version: String) : ShareLinkResult
}
